'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Categoria
    Public Property id_Categoria As Integer
    Public Property descripcion_Categoria As String
    Public Property tipo_Categoria As Integer
    Public Property estado_Categoria As Nullable(Of Integer)
    Public Property fecha_Creacion_Categoria As Date
    Public Property usuario_Creacion_Categoria As String
    Public Property fecha_Creacion_Actualizacion As Nullable(Of Date)
    Public Property usuario_Creacion_Actualizacion As String

End Class
