'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Comensal
    Public Property id_Comensal As Integer
    Public Property codigo_Comensal As String
    Public Property nombres_Comensal As String
    Public Property apellidos_Comensal As String
    Public Property area_Comensal As String
    Public Property puesto_Comensal As String
    Public Property estado_Comensal As Integer
    Public Property fecha_Creacion_Comensal As Date
    Public Property usuario_Creacion_Comensal As String
    Public Property fecha_Actualizacion_Comensal As Nullable(Of Date)
    Public Property usuario_Actualizacion As String

End Class
