'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empresa_Turno
    Public Property id_Empresa_Turno As Integer
    Public Property id_Sede_Turno As Integer
    Public Property id_Turno As String
    Public Property descripcion_Turno As String
    Public Property estado_Turno As Integer
    Public Property fecha_Creacion_Turno As Date
    Public Property usuario_Creacion_Turno As String
    Public Property fecha_Actualizacion_Turno As Nullable(Of Date)
    Public Property usuario_Actualizacion_Turno As String

End Class
