'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empresa_Sede
    Public Property id_Empresa_Sede As Integer
    Public Property id_Sede As Integer
    Public Property nombre_Sede As String
    Public Property direccion_Sede As String
    Public Property distrito_Sede As Nullable(Of Integer)
    Public Property provinicia_Sede As Nullable(Of Integer)
    Public Property departamento_Sede As Nullable(Of Integer)
    Public Property estado_Sese As Integer
    Public Property fecha_Creacion_Sede As Date
    Public Property usuario_Creacion_Sede As String
    Public Property fecha_Actualizacion_Sede As Nullable(Of Date)
    Public Property usuario_Actualizacion_Sede As String

End Class
