'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empresa
    Public Property id_Empresa As Integer
    Public Property razon_Social_Empresa As String
    Public Property rUC_Empresa As String
    Public Property direccion_Empresa As String
    Public Property distrito_Empresa As Integer
    Public Property provincia_Empresa As Integer
    Public Property departamento_Empresa As Integer
    Public Property telefono1_Empresa As String
    Public Property telefono2_Empresa As String
    Public Property contacto1_Empresa As String
    Public Property email1_Empresa As String
    Public Property contacto2_Empresa As String
    Public Property email2_Empresa As String
    Public Property estado_Empresa As Integer
    Public Property fecha_Creacion_Empresa As Date
    Public Property usuario_Creacion_Empresa As String
    Public Property fecha_Actualizacion_Empresa As Nullable(Of Date)
    Public Property usuario_Actualizacion_Empresa As String

End Class
