'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Estado
    Public Property id_Estado As Integer
    Public Property descripcion_Estado As String
    Public Property fecha_Creacion_Estado As Date
    Public Property usuario_Creacion_Estado As String

End Class
