'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Menu
    Public Property id_Menu As Integer
    Public Property descripcion_Menu As String
    Public Property costo_Estandar_Menu As Double
    Public Property costo_Real_Menu As Double
    Public Property precio_Venta_Menu As Double
    Public Property id_Categoria_Menu As Integer
    Public Property estado_Menu As Integer
    Public Property fecha_Creacion_Menu As Date
    Public Property usuario_Creacion_Menu As String
    Public Property fecha_Actualizacion_Menu As Nullable(Of Date)
    Public Property usuario_Actualizacion_Menu As String
    Public Property imagen_Menu As String

End Class
