'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Plato
    Public Property id_Plato As Integer
    Public Property descripcion_Plato As String
    Public Property id_Categoria_Plato As Integer
    Public Property costo_Estandar_Plato As Double
    Public Property costo_Real_Plato As Double
    Public Property precio_Venta_Plato As Double
    Public Property estado_Plato As Integer
    Public Property fecha_Creacion_Plato As Date
    Public Property usuario_Creacion_Plato As String
    Public Property fecha_Actualizacion_Plato As Nullable(Of Date)
    Public Property usuario_Actualizacion_Plato As String
    Public Property imagen_Plato As String

End Class
