'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Producto
    Public Property id_Producto As Integer
    Public Property descripcion_Producto As String
    Public Property id_Categoria_Producto As Integer
    Public Property stock_Producto As Double
    Public Property stock_Minimo_Producto As Double
    Public Property costo_Estandar_Producto As Double
    Public Property costo_Real_Producto As Double
    Public Property precio_Venta_Producto As Double
    Public Property estado_Producto As Integer
    Public Property fecha_Creacion_Producto As Date
    Public Property usuario_Creacion_Producto As String
    Public Property fecha_Actualizacion_Producto As Nullable(Of Date)
    Public Property usuario_Actualizacion_Producto As String
    Public Property imagen_Producto As String

End Class
