'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property id_Usuario As String
    Public Property nombres_Usuario As String
    Public Property apellidos_Usuario As String
    Public Property estado_Usuario As Nullable(Of Integer)
    Public Property fecha_Creacion_Usuario As Date
    Public Property usuario_Creacion_Usuario As String
    Public Property fecha_Actualizacion_Usuario As Nullable(Of Date)
    Public Property usuario_Actualizacion_Usuario As String

End Class
